### ISSUE TITLE
Is this project continue

### ISSUE THREAD

**Issue by takaaptech** [james7132/DanmakU#19]
I just found this bullet system and if you continue it will be greats!
Thank so much!

**Comment by james7132** [comment]
Unfortunately I am no longer actively maintaining this. It is also horribly out of date since it depends on the Unity particle system, which has been completely revamped since 5.3, the last version of Unity this project supports.

**Comment by takaaptech** [comment]
Great when see you come back! I am looking for this 👍

**Comment by james7132** [comment]
I'm restarting the project from scratch in Unity 5.6 on the develop branch. If you want to help out with the development, feel free to log feature request issues.
