### ISSUE TITLE
Missing References

### ISSUE THREAD

**Issue by pitaslayer** [james7132/DanmakU#20]
I know that you aren't supporting this package.

However I'm really interested in it. When I download the source cod project, there are some missing references in the hierarchy test scene (GameObject and Test). Can you tell me what are the scripts that are supposed to be there?

Kind Regards,

**Comment by james7132** [comment]
I'm not totally sure. It's been a long while since I've touched this project.

If there is enough interest in continuing support for it. I am willing to revive it, provided there are individuals that can help out via pull requests.

**Comment by pitaslayer** [comment]
Ok. I don't mind helping because I'm trying to make a rpg bullet hell from scratch. So if there is something that can help me achieve that :D

**Comment by james7132** [comment]
I'm restarting the project from scratch in Unity 5.6 on the `develop` branch. If you want to help out with the development, feel free to log feature request issues.
