### ISSUE TITLE
About the prefab

### ISSUE THREAD

**Issue by AliAkbarMontazeri** [james7132/DanmakU#21]
Hi, thanks for the great danmaku project you shared !
I want to ask about why the instantiated bullet doesn't appear in the hieararchy ?
I would really appreciate it if you are willing to answer this newbie question. Thank you !

**Comment by james7132** [comment]
For performance reasons, Danmaku are not fully formed GameObjects. The actual rendering is done via a singleton particle system, where each particle is a separate bullet controlled by a set of Danmaku objects. The collision is also manually done via Physics2D calls.
