### ISSUE TITLE
DanmakU colliders not working

### ISSUE THREAD

**Issue by AliAkbarMontazeri** [james7132/DanmakU#22]
Hi,
So I've just created a new game object as a ground with one of the collider script you created. I tried it with collider2D attached but still not working, Then I add rigidbody2D to it but still the same.
Can you help me please why this is not working for me ?

**Comment by james7132** [comment]
The code in the `master` branch is stale and outdated. It may very well be buggy.

I'm restarting the project from scratch in `develop`. If you would like some features to return. Please add a feature request issue.

**Comment by AliAkbarMontazeri** [comment]
Wow great ! I'll try to help as best as I can
