### ISSUE TITLE
Should we revive this project?

### ISSUE THREAD

**Issue by james7132** [james7132/DanmakU#28]
There has been recent interest in reviving DanmakU as a project after it fell into disrepair.

If you are interested, please respond or react for a vote of confidence.

**Comment by GhoulMage** [comment]
I am interested

**Comment by Kailang** [comment]
Yes, that will be great.

I am thinking about making a Danmaku Hell game that can be edited by the player. 
This library, if revived, will significantly ease the development.

**Comment by davyroelstraete** [comment]
I would also appreciate some help in creating a Danmaku game. My own code is running into the 500+ bullets performance issues...

**Comment by james7132** [comment]
After gaining much more experience with using Unity's system, I've pieced together several parts that need to be tackled to get this all working:

 * Restoring basic functionality (bullet movement, collision, rendering)
 * Separating the danmaku data from the underlying rendering and collision management system. New package will support multiple underlying backends:
   * GameObject standard - generic, uses most of Unity's systems. Good for low bullet counts. This is likely the first backend we implement.
   *  ParticleSystem - what was originally built. Could benefit from the expansion of the particle system since 5.2
   * Custom, pluggable backend (?)
 * Fireables API - for use in declaratively building bullet patterns. (i.e. `Fire(circle.Of(line.Of(bullet))).When(timer.Ticked()).Until(enemy.Dies())`)
 * Danmaku Emitter Components - For building simple patterns
 * Integration into Unity's animation system:
   * Making component values animate-able.
   * Add [Timeline](https://blogs.unity3d.com/2017/06/06/unity-2017-1-beta-feature-highlight-timeline-cinemachine/) integration via the UnityEngine.Playables API.
 * Building standard danmaku game elements like Player objects, score, lives, etc.

I'm going to need a lot of help in creating this. I've created a [Discord server](https://discord.gg/e9G43m2) for this project and will be working on the project in what free time I have between the other projects. If more people join in on this and comment on the design of the project, I'm more willing to invest more time to its development, otherwise I'll only work on it when I feel like I have free time.

If you are interested in helping implement any of the above, please join the provided server.

**Comment by james7132** [comment]
I've completed bullet movement, rendering, spawning, and a basic implementation of the Fireables API in the  `develop` branch. Feel free to take a look at the TestScript.cs. With some editor tweaking, it makes this:

![Danmaku](https://pbs.twimg.com/media/DHE0lCMV0AAHrzZ.jpg:large)

Code duplicated here:

```csharp
using System.Collections.Generic;
using UnityEngine;
using DanmakU.Fireables;

namespace DanmakU {

    public class TestScript : MonoBehaviour {

        [SerializeField]
        Circle circle;
        [SerializeField]
        Ring ring;
        [SerializeField]
        GameObject prefab;

        [SerializeField]
        DanmakuInitialState initialState;

        DanmakuPool danmaku;

        // Use this for initialization
        void Start () {
            var prefabFireable = new PrefabFireable(prefab, 10000);
            danmaku = prefabFireable.Pool;
            var fireable = ring.Of(circle).Of(prefabFireable);
            fireable.Fire(initialState);
        }

        void Update() {
            danmaku.UpdateDanmaku(Time.deltaTime);
            Debug.Log(danmaku.ActiveCount);
        }

    }

}
```

**Comment by jozistudio** [comment]
I'm developing a top-down shooting game. I'll branch and see what I can help.
Thank you for your effort when you were a uni student.
Thank you for your effort when you dont abandon your "child".
Quoc

**Comment by sokigakiya** [comment]
Awesome

**Comment by QBrute** [comment]
Yes please! =)

**Comment by adrianologyff7** [comment]
I'm really interested. It'll be great if it gets revived. :)

**Comment by Stevepunk** [comment]
+1

**Comment by Nurdraku** [comment]
Would be awesome. Very interested!

**Comment by james7132** [comment]
I will be doing some experimental rewrites of the project once the new ECS/C# jobs system goes live in Unity 2018.1.

**Comment by james7132** [comment]
![image](https://user-images.githubusercontent.com/3137680/36206231-7d8bc31a-1146-11e8-93e2-458e59b5c084.png)

I've successfully gotten a basic bullet simulation (movement only, no collision) working with the new C# jobs system in the 2018.1 beta. Pictured above is about 1500 square bullets being moved around at a latency of ~1ms. Easily supports upwards of 20,000+ bullets, which should be more than enough for any danmaku game.

The manager code for it can be seen here; https://github.com/james7132/DanmakU/blob/jobified-danmaku/Assets/src_new/DanmakuPool.cs. There's a test script in the same branch for it.

**Comment by james7132** [comment]
Closing this issue as I am definitely going to start work on the new version based on what was posted last night.

**Comment by Kailang** [comment]
Oh, my God. This is **AMAZING**.
Too bad the Job System is still in beta.
